

# Site
title: Lsxo
description: this is a blog website
author: FZB
language: zh-Hans
timezone:


# URL
root: /

# Directory
source_dir: source
public_dir: public
themes_dir: themes
pagination_dir: page


page_size: 10


# theme
theme: next

# Deployment
deploy:
type:

